'use client';

import { useEffect, useMemo, useState } from 'react';
import { Activity, Blocks, Clock3, Coins, Gem, Gauge, History, Shield, Sparkles, Target, Trophy, Users, WalletCards, Network } from 'lucide-react';
import { BrandMark, Crystal, DataIcon, Dragon, LiveBadge, MetricCard, Panel, ProgressLine, ScaleArt, SideStat, StatusPill, navItems } from './components';

type AnyMap = Record<string, any>;
type Status = { node?: AnyMap; mining?: AnyMap; round?: AnyMap; wallet?: AnyMap; blocks?: AnyMap[]; server?: AnyMap; workers?: AnyMap[]; ts?: number };
const n=(v:unknown)=>{const x=Number(v);return Number.isFinite(x)?x:0};
const first=(...v:unknown[])=>v.find(x=>x!==undefined&&x!==null&&x!=='');
const optional=(...v:unknown[])=>{const x=first(...v);if(x===undefined)return undefined;const y=Number(x);return Number.isFinite(y)?y:undefined};
const compact=(v:unknown)=>{const x=n(v);if(x>=1e9)return(x/1e9).toFixed(2)+'B';if(x>=1e6)return(x/1e6).toFixed(2)+'M';if(x>=1e3)return(x/1e3).toFixed(2)+'K';return x.toFixed(x<10?2:0)};
const hash=(v:unknown)=>{const x=n(v);if(x>=1e12)return(x/1e12).toFixed(2)+' TH/s';if(x>=1e9)return(x/1e9).toFixed(2)+' GH/s';if(x>=1e6)return(x/1e6).toFixed(2)+' MH/s';if(x>=1e3)return(x/1e3).toFixed(2)+' KH/s';return x.toFixed(1)+' H/s'};
const fix=(v:unknown)=>n(v).toFixed(8)+' FIX';
const epoch=(v:unknown)=>{if(typeof v==='number')return v>1e12?v/1000:v;if(typeof v==='string'){const x=Number(v);if(x>0)return x>1e12?x/1000:x;const d=Date.parse(v);return Number.isFinite(d)?d/1000:0}return 0};
const duration=(v:unknown)=>{const x=Math.max(0,Math.floor(n(v))),h=Math.floor(x/3600),m=Math.floor(x%3600/60),s=x%60;return h?`${h}h ${String(m).padStart(2,'0')}m`:`${m}m ${String(s).padStart(2,'0')}s`};
const timeOf=(v:unknown)=>{const e=epoch(v);return e?new Date(e*1000).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',second:'2-digit'}):String(v||'—')};
const usd=(v:unknown,rate:unknown)=>{const r=optional(rate);return r===undefined?'—':'$'+(n(v)*r).toFixed(2)};

export default function Home(){
 const[data,setData]=useState<Status>({}),[now,setNow]=useState(Date.now()),[error,setError]=useState(false);
 useEffect(()=>{let alive=true;const load=async()=>{try{const q=await fetch(`/api/status?ts=${Date.now()}`,{cache:'no-store'});if(!q.ok)throw Error();const j=await q.json();if(alive){setData(j);setError(false)}}catch{if(alive)setError(true)}};load();const p=window.setInterval(load,2000),t=window.setInterval(()=>setNow(Date.now()),1000);return()=>{alive=false;window.clearInterval(p);window.clearInterval(t)}},[]);
 const mining=data.mining||{},round=data.round||{},node=data.node||{},wallet=data.wallet||{},server=data.server||{},blocks=Array.isArray(data.blocks)?data.blocks:[],workers=Array.isArray(data.workers)?data.workers:[];
 const height=n(first(round.height,round.round_height,node.height));
 const roundNumber=first(round.round_number,round.round_id,round.round,round.number,round.id,height);
 const networkDifficulty=n(first(round.difficulty,node.difficulty,mining.network_difficulty)),bestShare=n(first(round.best_share,mining.best_share));
 const candidatePercent=networkDifficulty>0?Math.min(100,bestShare/networkDifficulty*100):0,accepted=n(mining.accepted),rejected=n(mining.rejected),totalShares=accepted+rejected,acceptance=totalShares?accepted/totalShares*100:undefined;
 const workerCount=optional(mining.worker_count,mining.workers),liveWorkers=workerCount??workers.length,hashrate=n(first(mining.hashrate_5m,mining.hashrate,mining.hashrate5m)),sharesMin=optional(mining.round_shares,mining.shares_min),luck=optional(round.luck_pct,round.network_luck,mining.network_luck);
 const started=epoch(first(round.started_at,round.round_started_at)),elapsedApi=optional(round.elapsed_seconds,round.elapsed,round.age_seconds),elapsed=elapsedApi??(started?Math.max(0,now/1000-started):undefined),target=optional(round.target_seconds,round.round_target_seconds),remaining=elapsed!==undefined&&target!==undefined?Math.max(0,target-elapsed):undefined;
 const candidateHeight=n(first(round.candidate_height,mining.candidate_height,height?height+1:0)),bestBlock=n(first(round.best_block_height,mining.best_block_height,blocks[0]?.height));
 const balance=n(first(wallet.total,wallet.balance,wallet.amount)),pending=n(first(wallet.pending_payout,wallet.pending,wallet.unpaid)),paid=n(first(wallet.total_paid,wallet.paid)),estimated=first(wallet.estimated_earnings,wallet.estimated),usdRate=first(wallet.usd_rate,wallet.fx_rate,server.usd_rate);
 const blessing=first(round.temple_blessing,mining.temple_blessing),uptime=first(server.uptime,node.uptime),serverTime=first(server.time,server.server_time)||new Date(now).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'}),recent=useMemo(()=>blocks.slice(0,7),[blocks]);
 return <main className="magical-shell">
  <aside className="left-rail"><BrandMark/><div className="rail-rule"/><nav className="rail-nav" aria-label="Dashboard">{navItems.map(([label,Icon],i)=><button key={label} className={`rail-link ${i===0?'active':''}`} type="button"><Icon size={17}/><span>{label}</span></button>)}</nav><div className="rail-crystal"><Gem size={38}/><span>FIX</span></div><div className="rail-footer"><span>NODE STATUS</span><StatusPill>{error?'DEGRADED':'ONLINE'}</StatusPill><span>UPTIME</span><strong>{String(uptime||'—')}</strong></div></aside>
  <div className="dashboard-column">
   <header className="topbar"><div className="mobile-brand"><Gem size={17}/> LIVESHARE</div><div className="topbar-title"><span>FIXEDCOIN</span><b>◆</b> LIVESHARE <em>SOLO MINING · MAGICAL NETWORK</em></div><LiveBadge degraded={error}/></header>
   <section className="hero-card magic-panel"><Dragon side="left"/><Dragon side="right"/><div className="hero-copy"><span className="eyebrow">ARCANE SOLO MINING NETWORK</span><h1>LIVESHARE</h1><p>SOLO MINING · MAGICAL NETWORK</p><div className="versus-grid"><div className="hero-difficulty purple"><span>BEST SHARE</span><small>DIFFICULTY</small><strong>{compact(bestShare)}</strong><b>{bestShare?`Best: ${bestShare.toLocaleString()}`:'Waiting for shares'}</b><ProgressLine value={candidatePercent}/><i>{candidatePercent.toFixed(2)}% of Network Target</i></div><div className="versus-medallion">VS</div><div className="hero-difficulty gold"><span>NETWORK TARGET</span><small>DIFFICULTY</small><strong>{compact(networkDifficulty)}</strong><b>{networkDifficulty?networkDifficulty.toLocaleString():'Waiting for node sync'}</b><ProgressLine value={networkDifficulty?Math.max(2,100-candidatePercent):0} tone="gold"/><i>{networkDifficulty?`${compact(Math.max(0,networkDifficulty-bestShare))} remaining`:'—'}</i></div></div></div><div className="round-panel"><span>CURRENT ROUND</span><strong>#{roundNumber?String(roundNumber).replace(/^#/,''):'—'}</strong><div><small><Clock3 size={12}/> ROUND TIME</small><b>{elapsed!==undefined?duration(elapsed):'—'}</b></div><div><small><Clock3 size={12}/> TIME REMAINING</small><b className="cyan">{remaining!==undefined?duration(remaining):'—'}</b></div><div><small><Activity size={12}/> ROUND STATUS</small><span className="active-pill">{String(first(round.status,round.state,'ACTIVE')).toUpperCase()}</span></div></div></section>
   <section className="forge-grid magic-panel"><div className="section-ribbon"><span>LIVE SHARE FORGE · REALTIME PROOF OF WORK</span><b>{hash(hashrate)}</b></div><div className="metric-stack"><MetricCard label="HASHRATE" value={hash(hashrate)} note="LIVE PERFORMANCE" icon={Gauge}/><MetricCard label="SHARES / MIN" value={sharesMin===undefined?'—':sharesMin.toFixed(1)} note="LAST 10 MIN" icon={Activity}/><MetricCard label="NETWORK LUCK" value={luck===undefined?'—':`${luck.toFixed(1)}%`} note={luck===undefined?'BACKEND DATA REQUIRED':'NETWORK AVERAGE'} tone="gold" icon={Target}/></div><div className="altar"><Crystal large/><h3>MAGICAL CORE</h3><small>FIXEDCOIN // LIVE HASH STREAM // SHA256</small></div><div className="metric-stack"><MetricCard label="ACCEPTED SHARES" value={accepted.toLocaleString()} note={acceptance===undefined?'THIS ROUND':`${acceptance.toFixed(1)}% ACCEPTANCE`} tone="green" icon={Shield}/><MetricCard label="REJECTED SHARES" value={rejected.toLocaleString()} note="THIS ROUND" tone="red" icon={Shield}/><MetricCard label="LIVE WORKERS" value={liveWorkers.toLocaleString()} note={liveWorkers?'CONNECTED':'WAITING'} tone="violet" icon={Users}/></div></section>
   <div className="feature-grid"><Panel title="BLOCK CANDIDATE" subtitle="Independent probability of a new block" icon={Trophy} className="candidate-panel"><div className="candidate-layout"><div className="candidate-copy"><strong>{candidatePercent.toFixed(3)}%</strong><span>PROGRESS TO BLOCK</span><div className="candidate-meta"><small>BEST BLOCK EVER</small><b>{bestBlock?`#${bestBlock.toLocaleString()}`:'—'}</b></div><div className="candidate-meta"><small>CANDIDATE HEIGHT</small><b>{candidateHeight?`#${candidateHeight.toLocaleString()}`:'—'}</b></div></div><Crystal/></div><ProgressLine value={candidatePercent}/></Panel><Panel title="BALANCE" subtitle="Your Magical Earnings" icon={WalletCards} className="balance-panel"><div className="balance-layout"><ScaleArt/><div className="balance-value"><strong>{fix(balance)}</strong><span>LIVESHARE</span><small>{usd(balance,usdRate)}</small></div></div></Panel></div>
   <Panel title="BLOCK HISTORY" subtitle="Chronicles of the Eternal Chain" icon={History} className="history-panel"><div className="history-toolbar"><span>{recent.length} RECORDS</span><span>LIVE CHAIN TELEMETRY</span></div><div className="history-table-wrap"><table className="table magic-table"><thead><tr><th>HEIGHT</th><th>TIME</th><th>DIFFICULTY</th><th>LUCK</th><th>SHARES</th><th>MINER</th><th>MAGIC HASH</th><th>REWARD</th></tr></thead><tbody>{recent.length?recent.map((b,i)=><tr key={`${b.height||i}-${i}`}><td>#{n(first(b.height,b.block_height)).toLocaleString()}</td><td>{timeOf(first(b.time,b.timestamp,b.created_at))}</td><td>{compact(first(b.difficulty,networkDifficulty))}</td><td className="green-text">{optional(b.luck)===undefined?'—':`+${optional(b.luck)!.toFixed(1)}%`}</td><td>{compact(first(b.shares,0))}</td><td>{String(first(b.miner,b.worker,b.miner_name,'—'))}</td><td className="hash-text">{String(first(b.hash,b.blockhash,b.magic_hash,'—')).slice(0,18)}</td><td>{n(first(b.reward,0)).toFixed(4)} FIX</td></tr>):<tr><td colSpan={8} className="empty-row">Waiting for block history telemetry…</td></tr>}</tbody></table></div></Panel>
  </div>
  <aside className="right-rail"><SideStat label="ESTIMATED EARNINGS" value={estimated===undefined?'—':fix(estimated)} note={usd(n(estimated),usdRate)} tone="violet" icon={Coins}/><SideStat label="PENDING PAYOUT" value={fix(pending)} note={usd(pending,usdRate)} tone="green" icon={WalletCards}/><SideStat label="TOTAL PAID" value={fix(paid)} note={usd(paid,usdRate)} tone="cyan" icon={Coins}/><SideStat label="WORKERS ONLINE" value={liveWorkers.toLocaleString()} note="CONNECTED" tone="gold" icon={Users}/><SideStat label="NETWORK UPTIME" value={String(uptime||'—')} note="NODE TELEMETRY" tone="violet" icon={Network}/><SideStat label="SERVER TIME" value={String(serverTime)} note="UTC / NODE CLOCK" tone="cyan" icon={Clock3}/>{blessing !== undefined && blessing !== null && blessing !== '' && <div className="blessing-card"><Sparkles size={19}/><span>TEMPLE BLESSING</span><strong>ACTIVE</strong><small>{String(blessing)}</small></div>}{workers.length>0&&<div className="worker-mini"><div><span>WORKERS</span><b>{workers.length}</b></div><div className="worker-dots">{workers.slice(0,12).map((worker,i)=><i key={i} title={String(first(worker.name,worker.worker,worker.miner,`worker-${i+1}`))}/>)}</div></div>}<div className="node-mini"><DataIcon kind="network"/><div><span>NODE</span><strong>{node.syncing||node.initial_sync?'SYNCING':'ONLINE'}</strong></div></div></aside>
 </main>;
}
