'use client';

import { useEffect, useMemo, useState, type ReactNode } from 'react';
import { motion } from 'framer-motion';

type AnyMap = Record<string, any>;
type Status = { node?: AnyMap; mining?: AnyMap; round?: AnyMap; wallet?: AnyMap; blocks?: AnyMap[]; server?: AnyMap; workers?: AnyMap[]; ts?: number };

const num = (v: any) => Number.isFinite(Number(v)) ? Number(v) : 0;
const first = (...values: any[]) => values.find(v => v !== undefined && v !== null && v !== '');
const compact = (v: any) => { const x = num(v); if (x >= 1e9) return (x / 1e9).toFixed(2) + 'B'; if (x >= 1e6) return (x / 1e6).toFixed(2) + 'M'; if (x >= 1e3) return (x / 1e3).toFixed(2) + 'K'; return x.toFixed(x < 10 ? 2 : 0); };
const hash = (v: any) => { const x = num(v); if (x >= 1e12) return (x / 1e12).toFixed(2) + ' TH/s'; if (x >= 1e9) return (x / 1e9).toFixed(2) + ' GH/s'; if (x >= 1e6) return (x / 1e6).toFixed(2) + ' MH/s'; if (x >= 1e3) return (x / 1e3).toFixed(2) + ' KH/s'; return x.toFixed(1) + ' H/s'; };
const fix = (v: any) => num(v).toFixed(8) + ' FIX';
const epoch = (v: any) => { if (typeof v === 'number') return v > 1e12 ? v / 1000 : v; if (typeof v === 'string') { const n = Number(v); if (n > 0) return n; const d = Date.parse(v); return Number.isFinite(d) ? d / 1000 : 0; } return 0; };
const duration = (s: any) => { const x = Math.max(0, Math.floor(num(s))); const h = Math.floor(x / 3600); const m = Math.floor((x % 3600) / 60); const sec = x % 60; return h ? `${h}h ${String(m).padStart(2,'0')}m` : `${m}m ${String(sec).padStart(2,'0')}s`; };
const timeOf = (v: any) => { const e = epoch(v); return e ? new Date(e * 1000).toLocaleTimeString([], { hour:'2-digit', minute:'2-digit', second:'2-digit' }) : String(v || '—'); };

function Glyph({ children, gold = false }: { children: ReactNode; gold?: boolean }) { return <span className={`glyph ${gold ? 'glyphGold' : ''}`}>{children}</span>; }

function Crystal({ large = false }: { large?: boolean }) {
  return <div className={`crystalScene ${large ? 'crystalLarge' : ''}`}><div className="crystalStars"/><div className="crystalOrbit o1"/><div className="crystalOrbit o2"/><div className="crystalOrbit o3"/><motion.div className="crystalGlow" animate={{scale:[.92,1.08,.92],opacity:[.45,.85,.45]}} transition={{duration:4,repeat:Infinity}}/><motion.div className="crystal" animate={{y:[0,-6,0],rotateY:[0,180,360]}} transition={{duration:8,repeat:Infinity,ease:'easeInOut'}}><span>FX</span></motion.div><div className="crystalBase"><i/><i/><i/></div></div>;
}

function Dragon({ side }: { side:'left'|'right' }) {
  const id = `d-${side}`;
  return <svg className={`dragon dragon-${side}`} viewBox="0 0 300 470" aria-hidden="true"><defs><linearGradient id={id} x1="0" y1="0" x2="1" y2="1"><stop stopColor={side==='left'?'#f0b4ff':'#91efff'}/><stop offset=".4" stopColor={side==='left'?'#7938c7':'#1e79c3'}/><stop offset="1" stopColor="#070819"/></linearGradient><filter id={`${id}-g`}><feGaussianBlur stdDeviation="4" result="b"/><feMerge><feMergeNode in="b"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><g filter={`url(#${id}-g)`}><path d="M153 451C89 430 43 383 57 319c8-36 51-47 50-83-1-38-51-51-42-96 8-39 47-73 94-76-35 26-38 57-10 72 34 18 79-1 90 38 11 39-34 68-23 105 11 36 67 57 58 105-7 38-31 58-71 67Z" fill={`url(#${id})`} stroke="#b991ff" strokeWidth="2"/><path d="M118 124L34 48l71 16 44-51 8 84M178 127l92-68-73 15-37-51-9 85" fill="none" stroke="#a978ff" strokeWidth="3" opacity=".7"/><circle cx="178" cy="117" r="6" fill="#fff"/><path d="M171 88l-19-21M181 88l19-21" stroke="#ffd86a" strokeWidth="3"/></g></svg>;
}
function ScaleArt() { return <svg className="scaleArt" viewBox="0 0 320 250" aria-hidden="true"><defs><linearGradient id="sg" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#fff1a0"/><stop offset=".45" stopColor="#d89c2f"/><stop offset="1" stopColor="#68400d"/></linearGradient></defs><path d="M160 22v178M122 200h76M104 218h112" stroke="url(#sg)" strokeWidth="8" strokeLinecap="round"/><circle cx="160" cy="26" r="14" fill="#100d19" stroke="#ffd86a" strokeWidth="3"/><path d="M52 72h216M78 72l-34 76q34 25 68 0L78 72M242 72l34 76q-34 25-68 0l34-76" fill="rgba(255,216,106,.08)" stroke="#d99e36" strokeWidth="5"/><circle cx="78" cy="148" r="10" fill="#65ffad"/><circle cx="242" cy="148" r="10" fill="#42d9ff"/></svg>; }
function Panel({ title, subtitle, children, className='' }: { title:string; subtitle?:string; children:ReactNode; className?:string }) { return <section className={`panel ${className}`}><div className="panelTitle"><div><h2>{title}</h2>{subtitle&&<p>{subtitle}</p>}</div><span>✧</span></div>{children}</section>; }
function Metric({ label, value, note, tone='' }: { label:string; value:string; note?:string; tone?:string }) { return <div className={`metric ${tone}`}><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}<div className="spark"><i/></div></div>; }
function SideStat({ label,value,tone }: { label:string;value:string;tone:string }) { return <div className={`sideStat ${tone}`}><span>{label}</span><strong>{value}</strong><small>LIVE TELEMETRY</small></div>; }

export default function Home() {
  const [data,setData]=useState<Status>({}); const [now,setNow]=useState(Date.now()); const [error,setError]=useState(false);
  useEffect(()=>{let alive=true;const load=async()=>{try{const r=await fetch('/api/status?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw new Error();const j=await r.json();if(alive){setData(j);setError(false)}}catch{if(alive)setError(true)}};load();const p=setInterval(load,2000);const t=setInterval(()=>setNow(Date.now()),1000);return()=>{alive=false;clearInterval(p);clearInterval(t)}},[]);
  const m=data.mining||{},r=data.round||{},node=data.node||{},w=data.wallet||{},server=data.server||{};const blocks=Array.isArray(data.blocks)?data.blocks:[];
  const roundHeight=num(first(r.height,r.round_height,node.height));
  const networkDiff=num(first(r.difficulty,node.difficulty,m.network_difficulty));
  const bestShare=num(first(r.best_share,m.best_share));
  const blockProgress=Math.min(100,networkDiff>0?bestShare/networkDiff*100:0);
  const accepted=num(m.accepted),rejected=num(m.rejected),workerCount=num(first(m.worker_count,m.workers,data.workers?.length));
  const totalShares=accepted+rejected;const acceptance=totalShares?accepted/totalShares*100:100;
  const started=epoch(first(r.started_at,r.round_started_at));const age=started?Math.max(0,now/1000-started):0;const targetSeconds=num(first(r.target_seconds,600))||600;const remaining=Math.max(0,targetSeconds-age);const overrun=Math.max(0,age-targetSeconds);
  const hashrate=num(first(m.hashrate_5m,m.hashrate,m.hashrate5m));const balance=num(first(w.total,w.balance,w.amount));const pending=num(first(w.pending_payout,w.pending,w.unpaid));const paid=num(first(w.total_paid,w.paid));const luck=num(first(r.luck_pct,r.network_luck,100));
  // These are deliberately independent: a round is an active mining epoch; a candidate is a possible next block.
  const candidateHeight=num(first(r.candidate_height,m.candidate_height,roundHeight+1));const bestBlockEver=num(first(r.best_block_height,m.best_block_height,blocks[0]?.height,roundHeight));
  const recent=useMemo(()=>blocks.slice(0,6),[blocks]);const status=node.online===false?'OFFLINE':error?'DEGRADED':'ONLINE';

  return <main className="appShell">
    <aside className="rail leftRail"><div className="crest">✦</div><div className="brand">FIXEDCOIN<small>SOLO NODE</small></div><div className="railLine"/><nav>{['Dashboard','Mining','Shares','Blocks','Workers','Settings','Logs','System'].map((x,i)=><div key={x} className={`nav ${i===0?'active':''}`}><Glyph>{['✦','◇','◌','▣','♙','⚙','≡','⬡'][i]}</Glyph>{x}</div>)}</nav><div className="railCrystal">◆</div><div className="railStatus"><small>NODE STATUS</small><b className={status==='ONLINE'?'online':''}><i/> {status}</b><small>UPTIME</small><strong>{server.uptime||'—'}</strong></div></aside>
    <section className="content"><header className="topbar"><div className="mobileBrand"><span>✦</span> LIVESHARE</div><div className="topTitle">LIVESHARE <em>✦</em> ARCANE FORGE</div><div className="live"><i/> {error?'API DEGRADED':'STRATUM · LIVE'}</div></header>
      <section className="hero panel"><Dragon side="left"/><Dragon side="right"/><div className="heroMain"><span className="eyebrow">ARCANE SOLO MINING NETWORK</span><h1>LIVESHARE</h1><p>SOLO MINING · MAGICAL NETWORK</p><div className="versus"><div className="heroStat purple"><label>BEST SHARE DIFFICULTY</label><strong>{compact(bestShare)}</strong><small>Best: {bestShare.toLocaleString()}</small><div className="progress purpleBar"><i style={{width:`${blockProgress}%`}}/></div><em>{blockProgress.toFixed(2)}% of Network Target</em></div><div className="vs">VS</div><div className="heroStat gold"><label>NETWORK TARGET DIFFICULTY</label><strong>{compact(networkDiff)}</strong><small>{networkDiff.toLocaleString()}</small><div className="progress goldBar"><i style={{width:`${Math.max(3,100-blockProgress)}%`}}/></div><em>{compact(Math.max(0,networkDiff-bestShare))} remaining</em></div></div></div><div className="roundCard"><label>CURRENT ROUND</label><strong>#{roundHeight.toLocaleString()}</strong><div><small>⌛ ROUND TIME</small><b>{started?duration(age):'—'}</b></div><div><small>⌛ TIME REMAINING</small><b className="cyan">{started?(overrun?`+${duration(overrun)}`:duration(remaining)):'—'}</b></div><div><small>ROUND STATUS</small><span className="statusPill">{node.online===false?'OFFLINE':'ACTIVE'}</span></div></div></section>
      <section className="forge panel"><div className="sectionBar"><span>LIVE SHARE FORGE · REALTIME PROOF OF WORK</span><b><i/> {hash(hashrate)}</b></div><div className="forgeGrid"><div className="metricStack"><Metric label="HASHRATE" value={hash(hashrate)} note="LIVE PERFORMANCE"/><Metric label="SHARES / MIN" value={num(first(m.round_shares,m.shares_min)).toFixed(1)} note="LAST 10 MIN"/><Metric label="NETWORK LUCK" value={`${luck.toFixed(1)}%`} note="ABOVE AVERAGE" tone="gold"/></div><div className="altar"><Crystal large/><h3>LIVESHARE <span>· ARCANE CORE</span></h3><small>MAGIC ENERGY // LIVE HASH STREAM // SHA256</small></div><div className="metricStack"><Metric label="ACCEPTED SHARES" value={accepted.toLocaleString()} note={`${acceptance.toFixed(1)}% ACCEPTANCE`} tone="green"/><Metric label="REJECTED SHARES" value={rejected.toLocaleString()} note={`−${rejected}`} tone="red"/><Metric label="LIVE WORKERS" value={workerCount.toLocaleString()} note={workerCount?'CONNECTED':'WAITING'} tone="violet"/></div></div></section>
      <div className="featureGrid"><Panel title="BLOCK CANDIDATE" subtitle="Magical probability of a new block" className="candidate"><div className="candidateTop"><div><strong>{blockProgress.toFixed(3)}%</strong><span>PROGRESS TO BLOCK</span><small>BEST BLOCK EVER <b>#{bestBlockEver.toLocaleString()}</b></small><small>CANDIDATE HEIGHT <b>#{candidateHeight.toLocaleString()}</b></small></div><Crystal/></div><div className="bigProgress"><i style={{width:`${blockProgress}%`}}/></div></Panel><Panel title="BALANCE" subtitle="Your Magical Earnings" className="balance"><div className="balanceVisual"><ScaleArt/><div><strong>{fix(balance)}</strong><span>LIVESHARE</span><small>≈ {num(balance*(num(w.usd_rate)||1)).toFixed(2)} USD</small></div></div></Panel></div>
      <Panel title="BLOCK HISTORY" subtitle="Chronicles of the Eternal Chain" className="history"><div className="records">{recent.length} RECORDS</div><div className="table"><div className="tr th"><span>HEIGHT</span><span>TIME</span><span>DIFFICULTY</span><span>LUCK</span><span>SHARES</span><span>MINER</span><span>MAGIC HASH</span><span>REWARD</span></div>{recent.map((b,i)=><div className="tr" key={`${b.height||i}-${i}`}><span>#{num(first(b.height,b.block_height)).toLocaleString()}</span><span>{timeOf(first(b.time,b.timestamp,b.created_at))}</span><span>{compact(first(b.difficulty,networkDiff))}</span><span className="greenText">+{num(first(b.luck,luck)).toFixed(1)}%</span><span>{compact(first(b.shares,0))}</span><span>{first(b.miner,b.worker,b.miner_name,'liveshare')}</span><span className="hashText">{String(first(b.hash,b.blockhash,b.magic_hash,'000000...')).slice(0,14)}…</span><span>{num(first(b.reward,0)).toFixed(4)} FIX</span></div>)}</div></Panel>
    </section>
    <aside className="rail rightRail"><SideStat label="ESTIMATED EARNINGS" value={fix(first(w.estimated_earnings,w.estimated,0))} tone="violet"/><SideStat label="PENDING PAYOUT" value={fix(pending)} tone="green"/><SideStat label="TOTAL PAID" value={fix(paid)} tone="cyan"/><SideStat label="WORKERS ONLINE" value={workerCount.toString()} tone="gold"/><SideStat label="NETWORK UPTIME" value={server.uptime||'—'} tone="violet"/><SideStat label="SERVER TIME" value={new Date().toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'})} tone="cyan"/><div className="blessing"><span>ARCANE BLESSING</span><strong>ACTIVE</strong><small>+12.5% LUCK</small><i>✦</i></div></aside>
  </main>;
}
