'use client';

import { useEffect, useState } from 'react';
import { motion } from 'framer-motion';

type Status={node?:any;mining?:any;round?:any;wallet?:any;blocks?:any[];server?:any;ts?:number};
const n=(v:any)=>Number(v)||0;
const compact=(v:any)=>{const x=n(v);if(x>=1e9)return(x/1e9).toFixed(2)+'B';if(x>=1e6)return(x/1e6).toFixed(2)+'M';if(x>=1e3)return(x/1e3).toFixed(2)+'K';return x.toFixed(x<10?2:0)};
const hash=(v:any)=>{const x=n(v);if(x>=1e12)return(x/1e12).toFixed(2)+' TH/s';if(x>=1e9)return(x/1e9).toFixed(2)+' GH/s';if(x>=1e6)return(x/1e6).toFixed(2)+' MH/s';if(x>=1e3)return(x/1e3).toFixed(2)+' KH/s';return x.toFixed(1)+' H/s'};
const coins=(v:any)=>n(v).toFixed(8)+' FIX';
const eta=(diff:any,hr:any)=>{const seconds=n(diff)*4294967296/n(hr);if(!seconds||!Number.isFinite(seconds))return '—';const d=Math.floor(seconds/86400),h=Math.floor(seconds%86400/3600),m=Math.floor(seconds%3600/60);return d?`~${d}d ${h}h`:h?`~${h}h ${m}m`:`~${m}m`};
const duration=(seconds:any)=>{const s=Math.max(0,Math.floor(n(seconds)));const h=Math.floor(s/3600),m=Math.floor((s%3600)/60),sec=s%60;return h?`${h}h ${String(m).padStart(2,'0')}m`:m?`${m}m ${String(sec).padStart(2,'0')}s`:`${sec}s`};
const epoch=(v:any)=>{if(typeof v==='number')return v>1e12?v/1000:v;if(typeof v==='string'){const x=Number(v);if(Number.isFinite(x)&&x>0)return x;const d=Date.parse(v);return Number.isFinite(d)?d/1000:0}return 0};
const time=(v:any)=>v?new Date(v*1000).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—';

function Dragon({side}:{side:'left'|'right'}){return <svg className={`dragon dragon-${side}`} viewBox="0 0 260 420" aria-hidden="true"><defs><linearGradient id={`dg-${side}`} x1="0" y1="0" x2="1" y2="1"><stop stopColor={side==='left'?'#c66cff':'#48eaff'}/><stop offset=".5" stopColor="#38226f"/><stop offset="1" stopColor="#07131f"/></linearGradient></defs><path d={side==='left'?'M188 396C102 374 62 321 83 262c11-30 49-37 43-76-7-42-58-48-48-94 7-31 42-55 79-43-29 19-30 45-9 57 25 15 63 3 69 34 7 38-35 60-22 93 12 30 57 45 50 88-5 31-24 56-57 75Z':'M72 396C158 374 198 321 177 262c-11-30-49-37-43-76 7-42 58-48 48-94-7-31-42-55-79-43 29 19 30 45 9 57-25 15-63 3-69 34-7 38 35 60 22 93-12 30-57 45-50 88 5 31 24 56 57 75Z'} fill={`url(#dg-${side})`} stroke="rgba(205,170,255,.7)" strokeWidth="2"/><circle cx={side==='left'?163:97} cy="97" r="5" fill="#fff"/><path d={side==='left'?'M130 220l-55 34 62-8 48 20':'M130 220l55 34-62-8-48 20'} fill="none" stroke="rgba(80,240,255,.5)" strokeWidth="3"/><path d="M110 70Q130 35 150 70" fill="none" stroke="#ffd86a" strokeWidth="2" opacity=".7"/></svg>}
function Scale(){return <svg className="scale-art" viewBox="0 0 260 190" aria-hidden="true"><defs><linearGradient id="goldScale" x1="0" y1="0" x2="1" y2="1"><stop stopColor="#fff0a0"/><stop offset=".45" stopColor="#d99b31"/><stop offset="1" stopColor="#704313"/></linearGradient></defs><path d="M130 22v130M102 154h56M92 166h76" stroke="url(#goldScale)" strokeWidth="7" strokeLinecap="round"/><circle cx="130" cy="27" r="12" fill="#1a1320" stroke="#ffd86a" strokeWidth="3"/><path d="M45 60h170M65 60l-28 60q28 23 56 0L65 60M195 60l-28 60q28 23 56 0l-28-60" fill="rgba(255,216,106,.09)" stroke="#d99b31" strokeWidth="4"/><circle cx="65" cy="125" r="9" fill="#64ffad"/><circle cx="195" cy="125" r="9" fill="#48eaff"/></svg>}

export default function Home(){
 const [s,setS]=useState<Status>({}); const [error,setError]=useState(false); const [last,setLast]=useState(0); const [flash,setFlash]=useState(false); const [clock,setClock]=useState(Date.now());
 useEffect(()=>{let alive=true;const load=async()=>{try{const r=await fetch('/api/status?ts='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error();const x=await r.json();if(alive){setS(x);setError(false);setLast(Date.now());setFlash(true);setTimeout(()=>setFlash(false),500)}}catch{if(alive)setError(true)}};load();const id=setInterval(load,2000);const tick=setInterval(()=>setClock(Date.now()),1000);return()=>{alive=false;clearInterval(id);clearInterval(tick)}},[]);
 const m=s.mining||{},r=s.round||{},node=s.node||{},w=s.wallet||{},blocks=s.blocks||[],server=s.server||{};
 const best=n(r.best_share||m.best_share), network=n(r.difficulty||node.difficulty), progress=Math.min(100,network?best/network*100:0), accepted=n(m.accepted), rejected=n(m.rejected), workers=n(m.worker_count), total=accepted+rejected;
 const recent=Array.isArray(blocks)?blocks.slice(0,8):[]; const acceptance=total?accepted/total*100:100; const targetLeft=Math.max(0,network-best);
 const roundStarted=epoch(r.started_at); const roundAge=roundStarted?Math.max(0,clock/1000-roundStarted):0;
 const expectedBlockSeconds=n(r.target_seconds)||600; const hashRate=n(m.hashrate_5m); const estimatedBlockSeconds=network&&hashRate?network*4294967296/hashRate:expectedBlockSeconds;
 const roundRemaining=Math.max(0,estimatedBlockSeconds-roundAge); const overrun=Math.max(0,roundAge-estimatedBlockSeconds);
 const roundClock=roundStarted?(overrun>0?`+${duration(overrun)}`:duration(roundRemaining)):'—';
 const roundClockLabel=roundStarted?(overrun>0?'OVERRUN':'EST. TIME LEFT'):'WAITING FOR ROUND';
 const menu=['Dashboard','Mining','Shares','Blocks','Workers','Settings','Logs','System'];
 return <main className="app liveshare">
  <aside className="sidebar"><div className="crest">✦</div><div className="sideBrand">FIXEDCOIN<small>SOLO NODE</small></div><nav>{menu.map((x,i)=><div key={x} className={`navItem ${i===0?'active':''}`}><span>{['◉','◇','◌','▣','♙','⚙','≡','⬡'][i]}</span>{x}</div>)}</nav><div className="sideBottom"><span>NODE STATUS</span><b><i/> ONLINE</b><span>UPTIME</span><strong>{server.uptime||'—'}</strong></div></aside>
  <div className="main">
   <div className="topbar"><div className="brand">LIVESHARE <span>✦</span> ARCANE FORGE</div><div className="live"><i className="dot"/> {error?'API DEGRADED':'STRATUM · LIVE'}</div></div>
   <section className="grid hero"><div className="panel heroMain"><Dragon side="left"/><Dragon side="right"/><div className="heroCenter"><div className="eyebrow">ARCANE SOLO MINING NETWORK</div><h1>Forge your next block.</h1><p className="sub">Real-time FixedCoin proof-of-work command center · cyber mythic edition.</p><div className="heroStats"><div className="metric"><label>BEST SHARE</label><strong>{compact(best)}</strong><small>Best: {best.toLocaleString()}</small></div><div className="vs">VS</div><div className="metric network"><label>NETWORK TARGET DIFFICULTY</label><strong>{compact(network)}</strong><small>{network.toLocaleString()}</small></div></div><div className="track"><motion.i animate={{width:`${progress}%`}} transition={{duration:.7}}/></div><div className="trackRow"><span>0</span><b>{progress.toFixed(3)}%</b><span>{compact(targetLeft)} remaining</span></div></div></div>
    <aside className="panel round"><div className="eyebrow">CURRENT ROUND</div><strong>#{n(r.height||node.height).toLocaleString()}</strong><div className="mini"><label>ROUND AGE</label><b>⌛ {roundStarted?duration(roundAge):'—'}</b></div><div className="mini"><label>{roundClockLabel}</label><b className={overrun>0?'':'cyan'}>⌛ {roundClock}</b></div><div className="mini"><label>ROUND STATUS</label><span className="status">{node.online?'ACTIVE':'DEGRADED'}</span></div></aside></section>
   <section className={`panel forge ${flash?'dataFlash':''}`}><div className="forgeHead"><div className="eyebrow">LIVE SHARE FORGE · REALTIME PROOF OF WORK</div><div className="live"><i className="dot"/> {hash(m.hashrate_5m)}</div></div><div className="forgeStage">
    <div className="side"><div className="card"><label>HASHRATE</label><strong>{hash(m.hashrate_5m)}</strong><small>LIVE PERFORMANCE</small><div className="spark"/></div><div className="card"><label>SHARES / MIN</label><strong>{n(m.round_shares).toFixed(1)}</strong><small>LAST 10 MIN</small><div className="spark"/></div><div className="card goldCard"><label>ROUND EFFORT</label><strong>{n(r.effort_pct||progress).toFixed(2)}%</strong><small>PROOF OF WORK</small></div></div>
    <div className="coreWrap"><div className="magicParticles"/><div className="coreGlow"/><div className="core"><div className="ring"/><div className="ring"/><div className="ring"/><motion.div className="crystal" animate={{scale:[1,1.05,1],rotateY:[0,180,360]}} transition={{duration:8,repeat:Infinity,ease:'easeInOut'}}/></div><div className="coreTitle">LIVESHARE <span>· ARCANE CORE</span></div><div className="coreSub">MAGIC ENERGY // LIVE HASH STREAM // SHA256</div></div>
    <div className="side"><div className="card counter"><label>ACCEPTED SHARES</label><strong>{accepted.toLocaleString()}</strong><small>{acceptance.toFixed(1)}% ACCEPTANCE</small><div className="spark"/></div><div className="card counter reject"><label>REJECTED SHARES</label><strong>{rejected.toLocaleString()}</strong><small>−{rejected}</small><div className="spark"/></div><div className="card workers"><label>LIVE WORKERS</label><strong>{workers}</strong><small>{workers?'CONNECTED':'WAITING'}</small></div></div>
   </div></section>
   <section className="treasurySection panel"><div className="heading treasuryHeading"><div className="sigil goldSigil">◈</div><div><h2>ARCANE TREASURY LEDGER</h2><p>Rewards, payout flow and recorded earnings · bound to wallet state</p></div><span className="treasuryState">LIVE ECONOMY</span></div><div className="treasuryRail"><motion.div className="treasuryMetric earnings" animate={{y:[0,-1,0]}} transition={{duration:4,repeat:Infinity,ease:'easeInOut'}}><label>ESTIMATED EARNINGS</label><strong>{coins(n(w.total_rewards)/Math.max(1,workers||1))}</strong><small>CHAIN REWARDS</small></motion.div><motion.div className="treasuryMetric pending" animate={{y:[0,-1,0]}} transition={{duration:4.5,repeat:Infinity,ease:'easeInOut',delay:.4}}><label>PENDING PAYOUT</label><strong>{coins(w.pending)}</strong><small>UNTRUSTED PENDING</small></motion.div><motion.div className="treasuryMetric paid" animate={{y:[0,-1,0]}} transition={{duration:5,repeat:Infinity,ease:'easeInOut',delay:.8}}><label>TOTAL PAID / REWARDS</label><strong>{coins(w.total_rewards)}</strong><small>RECORDED REWARDS</small></motion.div></div></section>
   <section className="statRail"><div className="railCard"><label>WORKERS ONLINE</label><strong>{workers}</strong><small>CONNECTED</small></div><div className="railCard violet"><label>SERVER TIME</label><strong>{time(server.epoch)}</strong><small>LOCAL NODE</small></div><div className="railCard blessing"><label>ARCANE BLESSING</label><strong>{node.synced?'ACTIVE':'SYNCING'}</strong><small>{node.synced?'CHAIN SYNCHRONIZED':'CHECK NODE'}</small></div></section>
   <section className="grid lower"><div className="panel candidate"><div className="heading"><div className="sigil">✦</div><div><h2>BLOCK CANDIDATE · ARCANE PROXIMITY</h2><p>Best submitted work measured against the current network target.</p></div></div><div className="candidateVisual"><div><motion.div className="candidateValue" animate={{textShadow:[`0 0 20px rgba(165,108,255,.2)`,`0 0 42px rgba(165,108,255,.6)`,`0 0 20px rgba(165,108,255,.2)`]}} transition={{duration:2.5,repeat:Infinity}}>{progress.toFixed(3)}%</motion.div><small>PROGRESS TO BLOCK · NEXT #{(n(r.height||node.height)+1).toLocaleString()}</small></div><div className="miniCrystal">◆</div></div><div className="track"><motion.i animate={{width:`${progress}%`}} transition={{duration:.7}}/></div></div>
    <div className="panel balance"><div className="heading"><div className="sigil goldSigil">◈</div><div><h2>ARCANE TREASURY</h2><p>Wallet state · live chain economy</p></div><span className="treasuryBound">3 LEDGER LINKS</span></div><div className="balanceArt"><Scale/></div><div className="balanceGrid"><div className="balanceItem"><label>CONFIRMED</label><strong className="green">{coins(w.confirmed)}</strong></div><div className="balanceItem"><label>PENDING</label><strong>{coins(w.pending)}</strong></div><div className="balanceItem"><label>IMMATURE</label><strong>{coins(w.immature)}</strong></div><div className="balanceItem"><label>TOTAL</label><strong>{coins(w.total)}</strong></div></div><div className="treasuryLinks"><span>ESTIMATED ↗</span><span>PAYOUT ↗</span><span>PAID ↗</span></div></div></section>
   <section className="panel history"><div className="heading"><div className="sigil">◆</div><div><h2>CHRONICLES OF THE FIXEDCOIN CHAIN</h2><p>Validated blocks · arcane confirmations · rewards · proof history</p></div><span className="recordCount">{recent.length} RECORDS</span></div><div className="table"><div className="row head"><span>HEIGHT</span><span>TIME</span><span>DIFFICULTY</span><span>ARCANE CONFIRMATIONS</span><span>REWARD</span><span>MINER / HASH</span></div>{recent.length?recent.map((b:any,i:number)=><div className="row" key={`${b.height}-${i}`}><span>#{n(b.height).toLocaleString()}</span><span>{b.time?new Date(b.time*1000).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit',second:'2-digit'}):'—'}</span><span>{compact(b.difficulty||b.work||best)}</span><span><b className="confirmMagic"><i>✦</i>{n(b.confirmations)} <em>/ {n(b.validity_target||100)}</em></b></span><span className="gold">{n(b.reward).toFixed(4)}</span><span title={b.blockhash||b.txid}>{String(b.worker||'solo').slice(0,14)} · {String(b.blockhash||b.txid||'—').slice(0,18)}…</span></div>):<div className="row"><span>Waiting for blocks…</span></div>}</div></section>
   <footer className="footer"><strong>LIVESHARE · FIXEDCOIN SOLO</strong><span>PEERS <b>{n(node.connections)}</b></span><span>NETWORK <b>{compact(network)}</b></span><span>ETA <b>{eta(network,n(m.hashrate_5m))}</b></span><span>SYNC <b>{node.synced?'YES':'CHECKING'}</b></span><span>REFRESH <b>{last?new Date(last).toLocaleTimeString():'—'}</b></span></footer>
  </div>
 </main>
}