#!/usr/bin/env python3
"""Make dashboard round/timer state originate only from real NEW ROUND state."""
from pathlib import Path
import re

APP=Path('/app/monitor/app.py'); JS=Path('/app/monitor/static/dashboard_v4.js')
app=APP.read_text(); js=JS.read_text(); changed_app=False; changed_js=False

# Backend: tolerate all current patch-chain variants and converge on the
# authoritative round_height/round_started fields produced by NEW ROUND logs.
# IMPORTANT: anchor this to the status() indentation. A plain `height=int(...)`
# search also matches `round_height=int(...)` inside parse_logs(), which caused
# the round-authority patch to rewrite its own NEW ROUND state assignment and
# produce a runtime NameError for log_job before it existed.
height_re=r'(?m)^    height=int\([^\n]+\);'
height_match=re.search(height_re,app)
if height_match and 'height=int(log_job.get("round_height") or stats.get("round_height")' not in height_match.group(0):
    old=height_match.group(0)
    new='    height=int(log_job.get("round_height") or stats.get("round_height") or info.get("blocks") or mininginfo.get("blocks") or 0);'
    app=app[:height_match.start()]+new+app[height_match.end():]; changed_app=True; print('patched dashboard height precedence: NEW ROUND first')

# The v4 backend patch adds round_started_at/epoch to log_job. Ensure the
# serialized round object consumes those authoritative fields.
round_pat=r'"round":\{"height":.*?"target_seconds":ROUND_SECONDS\}'
rm=re.search(round_pat,app)
if rm and '"source":"stratum-log"' not in rm.group(0):
    old=rm.group(0)
    h='int(log_job.get("round_height") or height)'
    new=(old.replace('"height":int(stats.get("round_height") or height)',f'"height":{h}')
            .replace('"started_at":stats.get("round_started_at")', '"started_at":log_job.get("round_started_at")')
            .replace('"target_seconds":ROUND_SECONDS','"started_epoch":log_job.get("round_started_epoch"),"source":"stratum-log","target_seconds":ROUND_SECONDS'))
    if new!=old: app=app.replace(old,new,1); changed_app=True; print('patched dashboard timer source: NEW ROUND log')

if changed_app: APP.write_text(app)

# Frontend: remove the synthetic round activity generated by every poll. The
# real SSE round event remains authoritative; if this code was already patched,
# leave it untouched.
old_activity="const roundKey=parseTime(r.started_epoch||r.started_at);if(roundKey&&roundKey!==lastRoundKey){lastRoundKey=roundKey;addActivity('round','ROUND STARTED','#'+Number(r.height||0).toLocaleString(),r.started_at?.slice(11)||'',`round-live-${roundKey}`)}"
if old_activity in js:
    js=js.replace(old_activity,"/* ROUND STARTED comes only from authoritative NEW ROUND events. */",1); changed_js=True; print('removed synthetic ROUND STARTED activity generator')
old_timer="function updateTimer(round){const target=Number(round?.target_seconds)||600,started=parseTime(round?.started_epoch||round?.started_at);"
new_timer="function updateTimer(round){const target=Number(round?.target_seconds)||600,started=parseTime(round?.started_epoch||round?.started_at);if(round?.source&&round.source!=='stratum-log'){$('timeRemain').textContent='00:00';$('timePct').textContent='0.0%';$('roundStatus').textContent='WAITING';$('roundStatus').className='status waiting';return}"
if old_timer in js and 'round.source!==\'stratum-log\'' not in js:
    js=js.replace(old_timer,new_timer,1); changed_js=True; print('hardened dashboard timer source')
if changed_js: JS.write_text(js)
print('dashboard round authority patch complete')
