#!/usr/bin/env python3
"""Install the complete repository-owned Arcane LiveShare presentation.

This is the final visual composition stage. It deliberately owns the DOM/CSS
needed by desktop and mobile instead of stacking another legacy visual patch.
Runtime data remains supplied by /api/status; visual animation never depends
on Discord/GhostBot success.
"""
from pathlib import Path

ROOT = Path('/app')
HTML_PATH = ROOT / 'monitor/templates/dashboard_v4.html'
CSS_PATH = ROOT / 'monitor/static/dashboard_v4_reference_complete.css'
JS_PATH = ROOT / 'monitor/static/dashboard_v4_reference_complete.js'

html = HTML_PATH.read_text(encoding='utf-8')

# Decorative reference layer: no external images, no raster assets, entirely CSS/SVG.
if 'id="referenceOrnaments"' not in html:
    ornament = '''\n<div id="referenceOrnaments" class="reference-ornaments" aria-hidden="true">\n  <div class="dragon dragon-left"><span class="dragon-eye"></span><span class="dragon-wing"></span><span class="dragon-spine"></span></div>\n  <div class="dragon dragon-right"><span class="dragon-eye"></span><span class="dragon-wing"></span><span class="dragon-spine"></span></div>\n</div>\n'''
    html = html.replace('<main class="dashboard reference-dashboard liveshare-dashboard">', ornament + '<main class="dashboard reference-dashboard liveshare-dashboard">', 1)

# Complete treasury / earnings surface, placed before the Chronicle.
if 'id="arcaneTreasury"' not in html:
    treasury = '''\n<section class="arcane-treasury panel" id="arcaneTreasury">\n  <div class="treasury-head">\n    <div class="section-heading"><span class="target-icon">✦</span><div><h2>ARCANE TREASURY</h2><p>Rewards, pending output and confirmed FixedCoin wealth.</p></div></div>\n    <div class="treasury-status"><i></i> WALLET LINKED · LIVE</div>\n  </div>\n  <div class="treasury-grid">\n    <article class="treasury-card earnings"><span>ESTIMATED EARNINGS</span><strong id="estimatedEarnings">—</strong><small>PROJECTED FROM LIVE SHARE FLOW</small><div class="treasury-glyph">✦</div></article>\n    <article class="treasury-card pending"><span>PENDING OUTPUT</span><strong id="pendingOutput">—</strong><small>UNCONFIRMED · WAITING FOR TRUST</small><div class="treasury-glyph">◈</div></article>\n    <article class="treasury-card paid"><span>TOTAL PAID / REWARDS</span><strong id="totalPaidRewards">—</strong><small>CONFIRMED REWARD HISTORY</small><div class="treasury-glyph">◆</div></article>\n    <article class="treasury-card balance"><span>ARCANE BALANCE</span><strong id="treasuryBalance">—</strong><small>CONFIRMED + PENDING + IMMATURE</small><div class="treasury-glyph">◇</div></article>\n  </div>\n</section>\n<section class="activity-reference panel" id="activityReference">\n  <div class="activity-head"><div class="section-heading"><span class="target-icon">◈</span><div><h2>RECENT ACTIVITY</h2><p>Live proof-of-work events from the FixedCoin forge.</p></div></div><span class="history-count">LIVE STREAM</span></div>\n  <div class="activity-reference-grid" id="activityReferenceGrid"><div class="activity-reference-empty">Waiting for live share events…</div></div>\n</section>\n'''
    html = html.replace('<section class="block-history panel" id="blockHistory">', treasury + '<section class="block-history panel" id="blockHistory">', 1)

# Replace the old five-column Chronicle header with the complete eight-column reference header.
old_header = '<div class="history-row history-labels"><span>HEIGHT</span><span>VALIDITY</span><span>CONFIRMATIONS</span><span>REWARD</span><span>BLOCK HASH</span></div>'
new_header = '<div class="history-row history-labels"><span>HEIGHT</span><span>TIME</span><span>DIFFICULTY</span><span>LUCK</span><span>SHARES</span><span>MINER</span><span>BLOCK HASH</span><span>REWARD</span></div>'
html = html.replace(old_header, new_header, 1)

# Load the complete responsive visual layer and runtime companion.
css_tag = '<link rel="stylesheet" href="/static/dashboard_v4_reference_complete.css?v=20260829-complete">'
if css_tag not in html:
    html = html.replace('</head>', css_tag + '\n</head>', 1)
js_tag = '<script defer src="/static/dashboard_v4_reference_complete.js?v=20260829-complete"></script>'
if js_tag not in html:
    html = html.replace('</body>', js_tag + '\n</body>', 1)

HTML_PATH.write_text(html, encoding='utf-8')

CSS_PATH.write_text(r'''/* Arcane LiveShare — complete responsive reference composition */
:root{--arc-bg:#010509;--arc-panel:#031016;--arc-panel2:#06151b;--arc-line:#164b58;--arc-cyan:#20e7ff;--arc-green:#54ff82;--arc-red:#ff5367;--arc-amber:#ffbd42;--arc-text:#e9fbfd;--arc-muted:#66838b;--arc-mono:"JetBrains Mono",ui-monospace,SFMono-Regular,Consolas,monospace;--arc-display:"Cinzel",Georgia,serif}
.reference-dashboard{width:min(1470px,calc(100vw - 24px));max-width:1470px;margin-inline:auto;box-sizing:border-box;gap:12px;overflow:visible}
.reference-dashboard *{box-sizing:border-box}.reference-dashboard .panel{position:relative;overflow:hidden;border:1px solid rgba(28,91,105,.78);border-radius:16px;background:linear-gradient(145deg,rgba(4,17,23,.98),rgba(1,6,10,.99));box-shadow:inset 0 0 0 1px rgba(32,230,255,.025),0 22px 70px rgba(0,0,0,.52)}
.reference-ornaments{position:fixed;inset:0;pointer-events:none;z-index:0;overflow:hidden}.reference-dashboard{position:relative;z-index:1}
.dragon{position:absolute;width:240px;height:150px;opacity:.17;filter:drop-shadow(0 0 18px rgba(50,255,125,.28));border:1px solid rgba(75,255,130,.38);clip-path:polygon(0 58%,18% 42%,28% 18%,43% 40%,60% 7%,69% 38%,100% 25%,84% 59%,100% 72%,69% 65%,54% 95%,43% 67%,22% 91%,28% 65%)}
.dragon-left{left:-50px;top:38vh;transform:scale(.9) rotate(-8deg)}.dragon-right{right:-50px;top:58vh;transform:scaleX(-.9) rotate(-8deg)}.dragon-eye{position:absolute;width:8px;height:8px;border-radius:50%;background:var(--arc-green);box-shadow:0 0 14px var(--arc-green);left:62%;top:39%}.dragon-wing{position:absolute;inset:12% 18% 38% 34%;border:1px solid rgba(32,231,255,.4);transform:skew(-18deg)}.dragon-spine{position:absolute;left:23%;right:23%;top:57%;border-top:1px dashed rgba(84,255,130,.42)}
.hero{display:grid!important;grid-template-columns:minmax(0,1fr) clamp(240px,20vw,285px);min-height:clamp(270px,21vw,330px)}.hero-main{min-width:0;padding:clamp(20px,2.2vw,32px)}.hero-values{display:grid;grid-template-columns:minmax(0,1fr) auto minmax(0,1fr);align-items:end;gap:clamp(10px,2vw,28px)}.hero-value strong{font-size:clamp(42px,5vw,74px)!important;line-height:.92}.hero-value span,.hero-value small,.round-panel span,.balance-card span,.stat>span{font-family:var(--arc-mono)}.versus{color:var(--arc-cyan);font:800 clamp(12px,1vw,15px) var(--arc-mono);text-shadow:0 0 16px rgba(32,231,255,.45)}
.target-track,.candidate-track{background:#031218;border:1px solid rgba(27,95,108,.9);box-shadow:inset 0 0 14px rgba(0,0,0,.65),0 0 16px rgba(31,220,239,.04)}.target-track i,.candidate-track i{background:linear-gradient(90deg,#21ff72,#1ee6ff);box-shadow:0 0 18px rgba(32,255,117,.5)}
.round-panel{min-width:0;padding:clamp(18px,2vw,28px);border-left:1px solid rgba(27,83,96,.8);background:linear-gradient(180deg,rgba(3,14,20,.98),rgba(1,8,12,.98));display:flex;flex-direction:column;justify-content:center}.round-id{font-size:clamp(26px,2.5vw,40px);color:var(--arc-green);font-family:var(--arc-mono)}.round-panel .remaining{font-size:clamp(28px,2.8vw,42px);color:var(--arc-cyan);font-family:var(--arc-mono)}
.forge-stage{height:clamp(500px,40vw,570px)!important;min-height:0!important}.forge-stage:before{content:"";position:absolute;inset:0;background:radial-gradient(circle at 50% 48%,rgba(54,255,128,.12),transparent 20%),radial-gradient(circle at 50% 52%,rgba(25,225,255,.09),transparent 45%),linear-gradient(180deg,rgba(0,20,27,.25),transparent 70%);pointer-events:none;z-index:2}.forge-center{min-width:0}.core-logo{animation:arcFloat 5s ease-in-out infinite}.core-orbit{animation-duration:16s!important}.vardiff-badge{backdrop-filter:blur(8px)}
@keyframes arcFloat{0%,100%{transform:translateZ(100px) translateY(0)}50%{transform:translateZ(100px) translateY(-8px)}}
.arcane-treasury,.activity-reference{padding:clamp(18px,2vw,28px)}.treasury-head,.activity-head{display:flex;align-items:center;justify-content:space-between;gap:18px;margin-bottom:16px}.treasury-status{font:700 9px var(--arc-mono);letter-spacing:.14em;color:var(--arc-green);white-space:nowrap}.treasury-status i{display:inline-block;width:7px;height:7px;border-radius:50%;background:var(--arc-green);box-shadow:0 0 12px var(--arc-green);margin-right:7px;animation:arcPulse 1.6s ease-in-out infinite}.treasury-grid{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:12px}.treasury-card{position:relative;min-width:0;min-height:130px;padding:18px;border:1px solid rgba(24,85,99,.78);border-radius:13px;background:linear-gradient(145deg,rgba(4,19,25,.94),rgba(1,7,11,.98));overflow:hidden;transition:transform .25s ease,border-color .25s ease,box-shadow .25s ease}.treasury-card:hover{transform:translateY(-3px);border-color:rgba(32,231,255,.5);box-shadow:0 14px 35px rgba(0,0,0,.4),0 0 22px rgba(32,231,255,.06)}.treasury-card:after{content:"";position:absolute;inset:auto -20% -65% -20%;height:90px;background:radial-gradient(ellipse,rgba(55,255,126,.12),transparent 65%)}.treasury-card>span{display:block;color:#829da4;font:700 8px var(--arc-mono);letter-spacing:.15em}.treasury-card>strong{display:block;margin-top:10px;max-width:calc(100% - 30px);overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:var(--arc-green);font:800 clamp(22px,2vw,30px) var(--arc-mono);text-shadow:0 0 14px rgba(84,255,130,.22)}.treasury-card.pending>strong{color:var(--arc-cyan)}.treasury-card.paid>strong{color:var(--arc-amber)}.treasury-card.balance>strong{color:var(--arc-green)}.treasury-card small{display:block;margin-top:8px;color:#5b747b;font:600 7px var(--arc-mono);letter-spacing:.08em}.treasury-glyph{position:absolute;right:17px;bottom:13px;color:rgba(84,255,130,.35);font-size:28px;text-shadow:0 0 18px rgba(84,255,130,.3)}
.activity-reference-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.activity-reference-row{display:grid;grid-template-columns:34px minmax(0,1fr) auto;align-items:center;gap:10px;min-height:54px;padding:8px 11px;border:1px solid rgba(24,72,84,.65);background:rgba(2,11,15,.72);font-family:var(--arc-mono)}.activity-reference-row .event-icon{display:grid;place-items:center;width:27px;height:27px;border:1px solid currentColor;border-radius:50%;font-weight:800}.activity-reference-row.ok{color:var(--arc-green)}.activity-reference-row.bad{color:var(--arc-red)}.activity-reference-row.round{color:var(--arc-cyan)}.activity-reference-row .event-label{color:#d8ecef;font-size:9px}.activity-reference-row small{display:block;color:#617b82;font-size:7px;margin-top:3px}.activity-reference-row time{color:#5d777e;font-size:8px}.activity-reference-empty{padding:18px;text-align:center;color:#59737b;font:600 9px var(--arc-mono);letter-spacing:.1em}
.history-table{width:100%;overflow:auto}.history-row{display:grid;grid-template-columns:.7fr 1.05fr .95fr .65fr .65fr 1.05fr 2fr .85fr;gap:10px;align-items:center;min-width:930px;padding:11px 10px;border-bottom:1px solid rgba(18,56,66,.55);font-family:var(--arc-mono);font-size:9px}.history-labels{color:#68848b;font-weight:800;font-size:8px;letter-spacing:.12em}.history-row .magicHash{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;color:#8bb6be}.history-row .reward{color:var(--arc-green)}
.stats-primary{grid-template-columns:repeat(3,minmax(0,1fr))!important}.balance-grid{grid-template-columns:repeat(5,minmax(0,1fr))!important}.footer{display:flex;flex-wrap:wrap;gap:12px 22px;justify-content:space-between}
@keyframes arcPulse{0%,100%{opacity:.45;transform:scale(.85)}50%{opacity:1;transform:scale(1)}}
@media (max-width:1100px){.hero{grid-template-columns:minmax(0,1fr) 240px!important}.forge-side{width:190px!important}.left-side{left:18px!important}.right-side{right:18px!important}.forge-center{left:195px!important;right:195px!important}.treasury-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.balance-grid{grid-template-columns:repeat(3,minmax(0,1fr))!important}}
@media (max-width:760px){.reference-dashboard{width:calc(100vw - 14px)!important;max-width:none!important;gap:9px!important}.hero{display:flex!important;flex-direction:column!important;min-height:0!important}.hero-main{padding:17px!important}.hero-values{grid-template-columns:1fr!important;gap:14px!important}.versus{display:none}.hero-value strong{font-size:clamp(38px,13vw,58px)!important}.target-track{margin-top:17px!important}.round-panel{border-left:0;border-top:1px solid rgba(27,83,96,.8);padding:17px;display:grid;grid-template-columns:1fr 1fr;gap:8px 16px}.round-panel .round-sep{display:none}.round-panel .round-id,.round-panel .remaining,.round-panel .estimate{font-size:25px}.forge-stage{height:auto!important;min-height:700px!important}.forge-side{position:absolute!important;width:calc(50% - 22px)!important;top:18px!important;bottom:auto!important;padding-top:0!important;gap:9px!important}.left-side{left:12px!important}.right-side{right:12px!important}.forge-metric,.forge-counter{width:100%!important;min-width:0!important;height:105px!important;min-height:105px!important;padding:11px!important}.forge-counter{height:96px!important;min-height:96px!important}.forge-metric>strong{font-size:19px!important}.forge-counter>strong{font-size:26px!important}.forge-center{left:0!important;right:0!important;top:205px!important;bottom:155px!important}.vardiff-badge{top:5px!important;min-width:155px!important;padding:9px 12px!important}.core-orbit{width:245px!important;height:245px!important}.core-orbit-b{width:300px!important;height:300px!important}.core-orbit-c{width:205px!important;height:205px!important}.core-logo{transform:scale(.78)!important}.core-title{top:67%!important;font-size:8px!important}.core-status{top:74%!important;font-size:6px!important}.forge-bottom{left:12px!important;right:12px!important;bottom:15px!important;height:115px!important}.forge-network-label{bottom:0!important;width:100%;text-align:center;white-space:normal!important;line-height:1.5}.combo{width:108px!important}.candidate{display:flex!important;flex-direction:column!important;height:auto!important;min-height:410px!important}.candidate-left{padding:19px!important}.candidate-core{min-height:180px!important;border-left:0!important;border-top:1px solid rgba(23,73,84,.72)!important}.stats-primary,.balance-grid{grid-template-columns:1fr!important}.stat{min-height:100px!important}.balance-card{min-height:90px!important}.treasury-grid{grid-template-columns:1fr!important}.treasury-head,.activity-head{align-items:flex-start;flex-direction:column}.treasury-status{align-self:flex-start}.activity-reference-grid{grid-template-columns:1fr}.history-row{min-width:860px}.footer{font-size:8px;justify-content:flex-start}.dragon{opacity:.09;transform:scale(.55)}.dragon-left{left:-100px}.dragon-right{right:-100px}}
@media (prefers-reduced-motion:reduce){.reference-dashboard *,.reference-dashboard *:before,.reference-dashboard *:after{animation-duration:.001ms!important;animation-iteration-count:1!important;scroll-behavior:auto!important;transition:none!important}}
''', encoding='utf-8')

JS_PATH.write_text(r'''(()=>{'use strict';
if(window.__FIXEDCOIN_REFERENCE_COMPLETE__)return;window.__FIXEDCOIN_REFERENCE_COMPLETE__=true;
const $=id=>document.getElementById(id);
const num=v=>Number(v)||0;
const fmt=v=>{const n=num(v);if(n>=1e9)return(n/1e9).toFixed(2)+'B';if(n>=1e6)return(n/1e6).toFixed(2)+'M';if(n>=1e3)return(n/1e3).toFixed(2)+'K';return n.toFixed(n<10?4:2)};
const pick=(o,paths)=>{for(const p of paths){let v=o;for(const k of p.split('.'))v=v?.[k];if(v!==undefined&&v!==null&&v!=='')return v}return null};
function set(id,value){const e=$(id);if(e)e.textContent=value==null?'—':String(value)}
function renderTreasury(s){const w=s.wallet||s.balance||{};const b=s.balances||{};const confirmed=pick(s,["wallet.confirmed","wallet.confirmed_balance","balances.confirmed","confirmed_balance"]);const pending=pick(s,["wallet.unconfirmed","wallet.unconfirmed_balance","wallet.pending","balances.unconfirmed","unconfirmed_balance"]);const immature=pick(s,["wallet.immature","wallet.immature_balance","balances.immature","immature_balance"]);const total=pick(s,["wallet.total","wallet.total_balance","balances.total","total_balance"]);const estimated=pick(s,["earnings.estimated","earnings.estimated_earnings","estimated_earnings","wallet.estimated_earnings"]);const paid=pick(s,["earnings.total_paid","earnings.paid","wallet.total_paid","total_paid","rewards.total_paid"]);set('estimatedEarnings',estimated==null?'—':fmt(estimated)+' FX');set('pendingOutput',pending==null?'—':fmt(pending)+' FX');set('totalPaidRewards',paid==null?'—':fmt(paid)+' FX');set('treasuryBalance',total==null?(confirmed==null?'—':fmt(num(confirmed)+num(pending)+num(immature))+' FX'):fmt(total)+' FX')}
function renderActivity(s){const host=$('activityReferenceGrid');if(!host)return;const events=Array.isArray(s.shares)?s.shares.slice(-8).reverse():[];const rows=events.map((x,i)=>{const ok=x.accepted!==false&&!x.rejected;const label=ok?'ACCEPTED SHARE':'REJECTED SHARE';const value=x.work??x.pool_diff??x.diff??0;const t=x.ts||x.time||'';return `<div class="activity-reference-row ${ok?'ok':'bad'}"><span class="event-icon">${ok?'✓':'×'}</span><span><b class="event-label">${label}</b><small>WORK ${fmt(value)} · LIVE FORGE</small></span><time>${String(t).slice(11,19)}</time></div>`}).join('');if(rows)host.innerHTML=rows;}
async function poll(){try{const r=await fetch('/api/status?ts='+Date.now(),{cache:'no-store'});if(!r.ok)return;const s=await r.json();renderTreasury(s);renderActivity(s)}catch(_){}}
window.addEventListener('resize',()=>document.documentElement.style.setProperty('--arc-vw',innerWidth+'px'),{passive:true});
poll();setInterval(poll,2000);
})();''', encoding='utf-8')

print('dashboard complete reference installed: responsive desktop/mobile, Arcane Treasury, earnings/pending/paid, activity, Chronicle 8-column layout, dragons, depth, glow and motion')
''')